before_script:
  # Exit one errors
  - set -e

  # Install Behat
  - cd ./behat
  - composer install
  - cd ..

  # Install webdriverCSS
  - cd ./visual-monitor
  - npm install
  - cd ..


script:
  # Live Monitoring tests
  - cd ./behat
  - ./bin/behat --tags=~wip
  - cd ..

  # Visual Regression tests
  # - cd ./visual-monitor
  # - PROVIDER_PREFIX=browserstack SELECTED_CAPS=chrome mocha
